// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: hostname_encoded_test_case.proto

package pathbuilding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostnameEncodedTestCase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrustGraph    uint32   `protobuf:"varint,1,opt,name=trust_graph,json=trustGraph,proto3" json:"trust_graph,omitempty"`
	SrcNode       uint32   `protobuf:"varint,2,opt,name=src_node,json=srcNode,proto3" json:"src_node,omitempty"`
	DstNode       uint32   `protobuf:"varint,3,opt,name=dst_node,json=dstNode,proto3" json:"dst_node,omitempty"`
	InvalidEdges  []uint32 `protobuf:"varint,4,rep,packed,name=invalid_edges,json=invalidEdges,proto3" json:"invalid_edges,omitempty"`
	InvalidReason uint32   `protobuf:"varint,5,opt,name=invalid_reason,json=invalidReason,proto3" json:"invalid_reason,omitempty"`
}

func (x *HostnameEncodedTestCase) Reset() {
	*x = HostnameEncodedTestCase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostname_encoded_test_case_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostnameEncodedTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostnameEncodedTestCase) ProtoMessage() {}

func (x *HostnameEncodedTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_hostname_encoded_test_case_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostnameEncodedTestCase.ProtoReflect.Descriptor instead.
func (*HostnameEncodedTestCase) Descriptor() ([]byte, []int) {
	return file_hostname_encoded_test_case_proto_rawDescGZIP(), []int{0}
}

func (x *HostnameEncodedTestCase) GetTrustGraph() uint32 {
	if x != nil {
		return x.TrustGraph
	}
	return 0
}

func (x *HostnameEncodedTestCase) GetSrcNode() uint32 {
	if x != nil {
		return x.SrcNode
	}
	return 0
}

func (x *HostnameEncodedTestCase) GetDstNode() uint32 {
	if x != nil {
		return x.DstNode
	}
	return 0
}

func (x *HostnameEncodedTestCase) GetInvalidEdges() []uint32 {
	if x != nil {
		return x.InvalidEdges
	}
	return nil
}

func (x *HostnameEncodedTestCase) GetInvalidReason() uint32 {
	if x != nil {
		return x.InvalidReason
	}
	return 0
}

var File_hostname_encoded_test_case_proto protoreflect.FileDescriptor

var file_hostname_encoded_test_case_proto_rawDesc = []byte{
	0x0a, 0x20, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x64, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x17, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x72, 0x75, 0x73, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x73, 0x72, 0x63, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x73,
	0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x73,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x5f, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0c, 0x69, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x45, 0x64, 0x67, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_hostname_encoded_test_case_proto_rawDescOnce sync.Once
	file_hostname_encoded_test_case_proto_rawDescData = file_hostname_encoded_test_case_proto_rawDesc
)

func file_hostname_encoded_test_case_proto_rawDescGZIP() []byte {
	file_hostname_encoded_test_case_proto_rawDescOnce.Do(func() {
		file_hostname_encoded_test_case_proto_rawDescData = protoimpl.X.CompressGZIP(file_hostname_encoded_test_case_proto_rawDescData)
	})
	return file_hostname_encoded_test_case_proto_rawDescData
}

var file_hostname_encoded_test_case_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hostname_encoded_test_case_proto_goTypes = []interface{}{
	(*HostnameEncodedTestCase)(nil), // 0: HostnameEncodedTestCase
}
var file_hostname_encoded_test_case_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hostname_encoded_test_case_proto_init() }
func file_hostname_encoded_test_case_proto_init() {
	if File_hostname_encoded_test_case_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hostname_encoded_test_case_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostnameEncodedTestCase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hostname_encoded_test_case_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hostname_encoded_test_case_proto_goTypes,
		DependencyIndexes: file_hostname_encoded_test_case_proto_depIdxs,
		MessageInfos:      file_hostname_encoded_test_case_proto_msgTypes,
	}.Build()
	File_hostname_encoded_test_case_proto = out.File
	file_hostname_encoded_test_case_proto_rawDesc = nil
	file_hostname_encoded_test_case_proto_goTypes = nil
	file_hostname_encoded_test_case_proto_depIdxs = nil
}
