name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.23.0'
    - name: Build
      working-directory: test-suites
      run: go build -v ./...

    - name: Test
      working-directory: test-suites
      run: |
        if [[ -n "$(find . -name '*.go' | xargs gofmt -d)" ]]; then echo "gofmt check failed"; exit 1; fi
        go vet ./...
        go test -v ./...
